/*
 * NewJPanel.java
 *
 * Created on 2007/11/11, 21:19
 */

package open.dolphin.client;

import java.awt.Container;
import javax.swing.GroupLayout;
import javax.swing.JComponent;

/**
 *
 * @author  kazm
 */
public class KartePanel1 extends Panel2 {

    /** Creates new form NewJPanel */
    public KartePanel1() {
        initComponents();
        GroupLayout layout = (GroupLayout) this.getLayout();
        layout.setLayoutStyle(new javax.swing.LayoutStyle() {
            @Override
            public int getPreferredGap(JComponent component1, JComponent component2, ComponentPlacement type, int position, Container parent) {
                return 0;
            }
            @Override
            public int getContainerGap(JComponent component, int position, Container parent) {
                return 0;
            }
        });
        // これをセットしないと，勝手に cut copy paste のポップアップがセットされてしまう.
        soaTextPane.putClientProperty("Quaqua.TextComponent.showPopup", false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        timeStampLabel = new javax.swing.JLabel();
        soaTextPane = new javax.swing.JTextPane();

        jPanel2.setMaximumSize(new java.awt.Dimension(55, 22));
        jPanel2.setMinimumSize(new java.awt.Dimension(55, 22));
        jPanel2.setPreferredSize(new java.awt.Dimension(55, 22));

        timeStampLabel.setText("jLabel1");
        jPanel2.add(timeStampLabel);

        soaTextPane.setMargin(new java.awt.Insets(10, 10, 10, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(soaTextPane, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(soaTextPane, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextPane soaTextPane;
    private javax.swing.JLabel timeStampLabel;
    // End of variables declaration//GEN-END:variables


    public javax.swing.JTextPane getSoaTextPane() {
        return soaTextPane;
    }

    public javax.swing.JLabel getTimeStampLabel() {
        return timeStampLabel;
    }

    public int getTimeStampPanelHeight() {
        return jPanel2.getPreferredSize().height;
    }

    public javax.swing.JPanel getTimeStampPanel () {
        return jPanel2;
    }
}
